### ISSUE TITLE
Provide django cache backend

### ISSUE THREAD

**Issue by ad-m** [duk3luk3/onion-py#3]
Hello,

I want notifiy I created django cache backend. The code is in https://github.com/ad-m/telescope/tree/master/django_onion_cache . Free to do what do you want. 

Greetings,

**Comment by duk3luk3** [comment]
I will take a look at that, thanks!

**Comment by duk3luk3** [comment]
Hi, I've finally gotten around to integrating this, could you test it? I don't have a django app ready that I can just drop this into ;-) It is in my feature/django-cache branch.

**Comment by duk3luk3** [comment]
@ad-m: you still around?

**Comment by ad-m** [comment]
Yes, it works great. https://tor-telescope.herokuapp.com/

**Comment by duk3luk3** [comment]
Ah great! I'll merge it and make a release.

**Comment by duk3luk3** [comment]
Merged and released! https://pypi.org/project/OnionPy
