### ISSUE TITLE
Version Mismatch with version 4

### ISSUE THREAD

**Issue by mdegrazia** [duk3luk3/onion-py#7]
Hello,

Thanks for a great library. I just started receiving this error. I think OnionOO must have updated to version 4 which OnionPy does not support yet?  Thanks!
![version_mismatch](https://cloud.githubusercontent.com/assets/6284925/23466978/fd0bd810-fe59-11e6-99c5-a175b85ed705.PNG)

**Comment by duk3luk3** [comment]
That's very interesting, seeing as I haven't received any announcement of OnionOO moving to version 4.

I must not be listening to the correct channels.

I will fix this asap.

**Comment by duk3luk3** [comment]
It seems that there was only a very small change that shouldn't actually affect onion-py (but would potentially affect any consumers of onion-py!). It does seem like a major backward-compat-breaking change so the major version incremet seems very appropriate.

Until I get out a new version, you can just "monkeypatch" `OOO_VERSION_MAJOR` of the `Manager` class. [It's defined here.](https://github.com/duk3luk3/onion-py/blob/master/onion_py/manager.py#L69)

In your interactive session, just doing `Manager.OOO_VERSION_MAJOR = 4` before creating a `Manager` instance should do the trick.

**Comment by mdegrazia** [comment]
Great! Thanks for the quick response.

**Comment by duk3luk3** [comment]
I pushed the update.

**Comment by mmckail** [comment]
I think i'm having the same issue, substituting in version 7 and version 4 respectively.

"onion_py.manager.MajorVersionMismatchError: Received OnionOO Document with version 7, this library only supports up to version 4"
Any help would be greatly appreciated.
Thanks.
