### ISSUE TITLE
Get uptime in date values

### ISSUE THREAD

**Issue by demyan0** [duk3luk3/onion-py#9]
Hello, how can i get an uptime of any relay (days/hours). Wrapper gives me only this (graph values):
```
>>> print u.relays[1].uptime
{u'1_month': <onion_py.objects.GraphHistory instance at 0x7f5a1d9c0f80>, u'3_months': <onion_py.objects.GraphHistory instance at 0x7f5a1d9c6128>, u'5_years': <onion_py.objects.GraphHistory instance at 0x7f5a1d9c6050>, u'1_week': <onion_py.objects.GraphHistory instance at 0x7f5a1d9c6098>, u'1_year': <onion_py.objects.GraphHistory instance at 0x7f5a1d9c0fc8>}
```
Is it possible to get uptime in days/hours? i'm racking my brains..

**Comment by duk3luk3** [comment]
Hi,

you can infer the uptime by using the `last_restarted` field.

Like this:

```python
>>> from onion_py.manager import Manager
>>> s = Manager().query('details', limit=4)
>>> s.relays[0].last_restarted
'2017-09-22 11:08:08'
```

You'll want to parse that into a `datetime` using [strptime](https://docs.python.org/2/library/datetime.html#datetime.datetime.strptime) and then you can subtract it from `datetime.utcnow()` to get the uptime.

**Comment by demyan0** [comment]
Thanks for reply, duk3luk3! I'm trying something like this, it helped me
